sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - coverage
before_install:
  - npm update
install:
  - npm install
script:
  - npm run coveralls
